version: '3'
services:
  frontend:
    image: harshal1903/frontend-app:latest
    ports:
      - 4200:4200
    networks:
      - app-network

  backend:
    # build:
    #   dockerfile: backend/Dockerfile-node
    image: harshal1903/backend-app:latest
    ports:
      - 3003:3000
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:


# net stop winnat