version: "3"
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - node-backend
  node-backend:
    build:
      context: backend
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/gymusers
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
