# Use an official Node.js image as the base
FROM node:16.15

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files to the working directory
COPY package*.json ./
COPY package-lock.json .

# Clear npm cache
RUN npm cache clean --force
RUN npm install --legacy-peer-deps


# Install Node.js backend dependencies
RUN npm install @angular-devkit/build-angular
RUN npm install @angular/compiler-cli

RUN npm install --force

# Copy the entire backend code to the working directory
COPY . .

# Expose the backend's default port (adjust if necessary)
EXPOSE 3000

# Start the backend server
CMD ["node", "server.js"]
